[build]
  command = "npm run build" # Adjust to your build script
  publish = "build"         # Directory with static assets
  functions = "netlify/functions" # Functions directory

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200