// src/context/LanguageContext.js
import React, { createContext, useState, useContext, useEffect } from "react";

// Translation data
const translations = {
  en: {
    Home: "Home",
    "Add Recipe": "Add Recipe",
    Profile: "Profile",
    Admin: "Admin",
    Logout: "Logout",
    Login: "Login",
    Register: "Register",
    "Recipe Sharing": "Recipe Sharing",
    "My Recipes": "My Recipes",
    View: "View",
    Edit: "Edit",
    Delete: "Delete",
    "Explore Recipes": "Explore Recipes",
    "Search recipes...": "Search recipes...",
    "All Categories": "All Categories",
    Breakfast: "Breakfast",
    Lunch: "Lunch",
    Dinner: "Dinner",
    Dessert: "Dessert",
    "View Recipe": "View Recipe",
    "Edit Recipe": "Edit Recipe",
    "Update Recipe": "Update Recipe",
    "Add a Recipe": "Add a Recipe",
    Title: "Title",
    Description: "Description",
    Ingredients: "Ingredients",
    Steps: "Steps",
    Category: "Category",
    "Recipe Image (optional)": "Recipe Image (optional)",
    Comments: "Comments",
    "Post Comment": "Post Comment",
    "Add a comment...": "Add a comment...",
    "Please log in to view your profile.":
      "Please log in to view your profile.",
    "Admin Panel - Manage Recipes": "Admin Panel - Manage Recipes",
    Email: "Email",
    Password: "Password",
    "Invalid email or password.": "Invalid email or password.",
    "Failed to register. Try again.": "Failed to register. Try again.",
    "Repeat Password": "Repeat Password",
    "Repeat your password": "Repeat your password",
    "Passwords do not match.": "Passwords do not match.",
    "Enter your email": "Enter your email",
    "Enter your password": "Enter your password",
    "Recipe title": "Recipe title",
    "Recipe description": "Recipe description",
    "Recipe ingredients": "Recipe ingredients",
    "Recipe steps": "Recipe steps",
    "Recipe category": "Recipe category",
    "Recipe image": "Recipe image",
    "Recipe comments": "Recipe comments",
    "Post a comment": "Post a comment",
    "Add a comment": "Add a comment",
    "Describe your recipe": "Describe your recipe",
    "List ingredients, one per line": "List ingredients, one per line",
    "List steps, one per line": "List steps, one per line",
    "Select a category": "Select a category",
    Previous: "Previous",
    Next: "Next",
    "No recipes found.": "No recipes found.",
    "No comments yet.": "No comments yet.",
    "Recipe App": "Recipe Sharing Platform",
    "Update your recipe details.": "Update your recipe details.",
    "Share your favorite recipe with the world!":
      "Share your favorite recipe with the world!",
    "Discover and share amazing recipes!":
      "Discover and share amazing recipes!",
    "Log in to access your recipes!": "Log in to access your recipes!",
    "Manage all recipes as an admin.": "Manage all recipes as an admin.",
    "View your personal recipe collection!":
      "View your personal recipe collection!",
    "Create an account to share your recipes!":
      "Create an account to share your recipes!",
    "Related Recipes": "Related Recipes",
    "Recipe not found.": "Recipe not found.",
    "404 - Page Not Found": "404 - Page Not Found",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Sorry, the page you are looking for does not exist or has been moved.",
    "Back to Home": "Back to Home",
    "Sort by...": "Sort by...",
    "Alphabetical (A-Z)": "Alphabetical (A-Z)",
    "Alphabetical (Z-A)": "Alphabetical (Z-A)",
    "Date (Oldest First)": "Date (Oldest First)",
    "Date (Newest First)": "Date (Newest First)",
    "Register with Google": "Register with Google",
    "Login with Google": "Login with Google",
    "Failed to register with Google. Try again.":
      "Failed to register with Google. Try again.",
    "Failed to login with Google. Try again.":
      "Failed to login with Google. Try again.",
    Instructions: "Instructions",
    "Privacy Policy": "Privacy Policy",
    "YouTube Video URL (optional)": "YouTube Video URL (optional)",
    "Invalid YouTube URL": "Invalid YouTube URL",
    "Video Tutorial": "Video Tutorial",
    Username: "Username",
    "Enter your username": "Enter your username",
    "Account Settings": "Account Settings",
    "Current Password": "Current Password",
    "Enter your current password": "Enter your current password",
    "New Password": "New Password",
    "Enter your new password": "Enter your new password",
    "Confirm New Password": "Confirm New Password",
    "Repeat your new password": "Repeat your new password",
    "Update Password": "Update Password",
    "Delete Account": "Delete Account",
    "Confirm Account Deletion": "Confirm Account Deletion",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.",
    Cancel: "Cancel",
    "My Profile": "My Profile",
    "Update Username": "Update Username",
    "Username updated successfully.": "Username updated successfully.",
    "Failed to update username. Try again.":
      "Failed to update username. Try again.",
    "Password updated successfully.": "Password updated successfully.",
    "Failed to update password. Check your current password.":
      "Failed to update password. Check your current password.",
    "Account deleted successfully.": "Account deleted successfully.",
    "Failed to delete account. Check your current password.":
      "Failed to delete account. Check your current password.",
    "Manage your account and view your recipes!":
      "Manage your account and view your recipes!",
    "Failed to register: ": "Failed to register: ",
    "Failed to register with Google: ": "Failed to register with Google: ",
    "Invalid email or password: ": "Invalid email or password: ",
    "Failed to login with Google: ": "Failed to login with Google: ",
    "Username must be 20 characters or less.":
      "Username must be 20 characters or less.",
    "Session expired. Please log in again.":
      "Session expired. Please log in again.",
    "Error updating password:": "Error updating password:",
    "The current password is incorrect.": "The current password is incorrect.",
    "Too many attempts. Please try again later.":
      "Too many attempts. Please try again later.",
    "Password should be at least 6 characters.":
      "Password should be at least 6 characters.",
    "Failed to update password: ": "Failed to update password: ",
    "Please log in to add a comment.": "Please log in to add a comment.",
    "Invalid email or password": "Invalid email or password",
    Author: "Author",
  },
  vi: {
    Home: "Trang chủ",
    "Add Recipe": "Thêm công thức",
    Profile: "Hồ sơ",
    Admin: "Quản trị",
    Logout: "Đăng xuất",
    Login: "Đăng nhập",
    Register: "Đăng ký",
    "Recipe Sharing": "Chia sẻ món ăn",
    "My Recipes": "Công thức của tôi",
    View: "Xem",
    Edit: "Chỉnh sửa",
    Delete: "Xóa",
    "Explore Recipes": "Khám phá công thức",
    "Search recipes...": "Tìm kiếm công thức...",
    "All Categories": "Tất cả danh mục",
    Breakfast: "Bữa sáng",
    Lunch: "Bữa trưa",
    Dinner: "Bữa tối",
    Dessert: "Tráng miệng",
    "View Recipe": "Xem công thức",
    "Edit Recipe": "Chỉnh sửa công thức",
    "Update Recipe": "Cập nhật công thức",
    "Add a Recipe": "Thêm công thức mới",
    Title: "Tiêu đề",
    Description: "Mô tả",
    Ingredients: "Nguyên liệu",
    Steps: "Các bước",
    Category: "Danh mục",
    "Recipe Image (optional)": "Hình ảnh công thức (tùy chọn)",
    Comments: "Bình luận",
    "Post Comment": "Đăng bình luận",
    "Add a comment...": "Thêm bình luận...",
    "Please log in to view your profile.":
      "Vui lòng đăng nhập để xem hồ sơ của bạn.",
    "Admin Panel - Manage Recipes": "Bảng quản trị - Quản lý công thức",
    Email: "Email",
    Password: "Mật khẩu",
    "Invalid email or password.": "Email hoặc mật khẩu không hợp lệ.",
    "Failed to register. Try again.": "Đăng ký thất bại. Thử lại.",
    "Repeat Password": "Nhập lại mật khẩu",
    "Repeat your password": "Nhập lại mật khẩu của bạn",
    "Passwords do not match.": "Mật khẩu không khớp.",
    "Enter your email": "Nhập email của bạn",
    "Enter your password": "Nhập mật khẩu của bạn",
    "Recipe title": "Tên công thức",
    "Recipe description": "Mô tả công thức",
    "Recipe ingredients": "Nguyên liệu công thức",
    "Recipe steps": "Các bước công thức",
    "Recipe category": "Danh mục công thức",
    "Recipe image": "Hình ảnh công thức",
    "Recipe comments": "Bình luận công thức",
    "Post a comment": "Đăng bình luận",
    "Add a comment": "Thêm bình luận",
    "Describe your recipe": "Mô tả công thức của bạn",
    "List ingredients, one per line":
      "Liệt kê nguyên liệu, mỗi dòng một nguyên liệu",
    "List steps, one per line": "Liệt kê các bước, mỗi dòng một bước",
    "Select a category": "Chọn một danh mục",
    Previous: "Trước",
    Next: "Sau",
    "No recipes found.": "Không có công thức nào.",
    "No comments yet.": "Chưa có bình luận nào.",
    "Recipe App": "Nền tảng chia sẻ công thức nấu ăn",
    "Update your recipe details.":
      "Cập nhật thông tin chi tiết về công thức của bạn.",
    "Share your favorite recipe with the world!":
      "Chia sẻ công thức yêu thích của bạn với thế giới!",
    "Discover and share amazing recipes!":
      "Khám phá và chia sẻ những công thức tuyệt vời!",
    "Log in to access your recipes!": "Đăng nhập để xem công thức của bạn!",
    "Manage all recipes as an admin.":
      "Quản lý tất cả công thức như một quản trị viên.",
    "View your personal recipe collection!":
      "Xem bộ sưu tập công thức cá nhân của bạn!",
    "Create an account to share your recipes!":
      "Tạo tài khoản để chia sẻ công thức của bạn!",
    "Related Recipes": "Công thức liên quan",
    "Recipe not found.": "Không tìm thấy công thức.",
    "404 - Page Not Found": "404 - Trang không tồn tại",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Xin lỗi, trang bạn đang tìm không tồn tại hoặc đã được chuyển đi.",
    "Back to Home": "Quay về trang chủ",
    "Sort by...": "Sắp xếp theo...",
    "Alphabetical (A-Z)": "Theo thứ tự chữ cái (A-Z)",
    "Alphabetical (Z-A)": "Theo thứ tự chữ cái (Z-A)",
    "Date (Oldest First)": "Ngày (Cũ nhất trước)",
    "Date (Newest First)": "Ngày (Mới nhất trước)",
    "Register with Google": "Đăng ký với Google",
    "Login with Google": "Đăng nhập với Google",
    "Failed to register with Google. Try again.":
      "Đăng ký với Google thất bại. Thử lại.",
    "Failed to login with Google. Try again.":
      "Đăng nhập với Google thất bại. Thử lại.",
    Instructions: "Hướng Dẫn",
    "Privacy Policy": "Chính Sách Bảo Mật",
    "YouTube Video URL (optional)": "Liên kết video YouTube (tùy chọn)",
    "Invalid YouTube URL": "Liên kết YouTube không hợp lệ",
    "Video Tutorial": "Video hướng dẫn",
    Username: "Tên người dùng",
    "Enter your username": "Nhập tên người dùng của bạn",
    "Account Settings": "Thiết lập tài khoản",
    "Current Password": "Mật khẩu hiện tại",
    "Enter your current password": "Nhập mật khẩu hiện tại của bạn",
    "New Password": "Mật khẩu mới",
    "Enter your new password": "Nhập mật khẩu mới của bạn",
    "Confirm New Password": "Xác nhận mật khẩu mới",
    "Repeat your new password": "Nhập lại mật khẩu mới của bạn",
    "Update Password": "Cập nhật mật khẩu",
    "Delete Account": "Xóa tài khoản",
    "Confirm Account Deletion": "Xác nhận xóa tài khoản",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "Bạn có chắc chắn muốn xóa tài khoản của mình không? Hành động này không thể hoàn tác và tất cả công thức của bạn sẽ bị xóa.",
    Cancel: "Hủy bỏ",
    "My Profile": "Hồ sơ của tôi",
    "Update Username": "Cập nhật tên người dùng",
    "Username updated successfully.":
      "Tên người dùng đã được cập nhật thành công.",
    "Failed to update username. Try again.":
      "Cập nhật tên người dùng thất bại. Thử lại.",
    "Password updated successfully.": "Mật khẩu đã được cập nhật thành công.",
    "Failed to update password. Check your current password.":
      "Cập nhật mật khẩu thất bại. Kiểm tra mật khẩu hiện tại của bạn.",
    "Account deleted successfully.": "Tài khoản đã được xóa thành công.",
    "Failed to delete account. Check your current password.":
      "Xóa tài khoản thất bại. Kiểm tra mật khẩu hiện tại của bạn.",
    "Manage your account and view your recipes!":
      "Quản lý tài khoản của bạn và xem công thức của bạn!",
    "Failed to register: ": "Đăng ký thất bại: ",
    "Failed to register with Google: ": "Đăng ký với Google thất bại: ",
    "Invalid email or password: ": "Email hoặc mật khẩu không hợp lệ: ",
    "Failed to login with Google: ": "Đăng nhập với Google thất bại: ",
    "Username must be 20 characters or less.":
      "Tên người dùng phải có độ dài tối đa 20 ký tự.",
    "Session expired. Please log in again.":
      "Phiên đã hết hạn. Vui lòng đăng nhập lại.",
    "Error updating password:": "Lỗi khi cập nhật mật khẩu:",
    "The current password is incorrect.": "Mật khẩu hiện tại không đúng.",
    "Too many attempts. Please try again later.":
      "Quá nhiều lần thử. Vui lòng thử lại sau.",
    "Password should be at least 6 characters.":
      "Mật khẩu phải có ít nhất 6 ký tự.",
    "Failed to update password: ": "Cập nhật mật khẩu thất bại: ",
    "Please log in to add a comment.": "Vui lòng đăng nhập để thêm bình luận.",
    "Invalid email or password": "Email hoặc mật khẩu không hợp lệ",
    Author: "Tác giả",
  },
  fr: {
    Home: "Accueil",
    "Add Recipe": "Ajouter une recette",
    Profile: "Profil",
    Admin: "Admin",
    Logout: "Déconnexion",
    Login: "Connexion",
    Register: "S'inscrire",
    "Recipe Sharing": "Partage de recettes",
    "My Recipes": "Mes recettes",
    View: "Voir",
    Edit: "Modifier",
    Delete: "Supprimer",
    "Explore Recipes": "Explorer les recettes",
    "Search recipes...": "Rechercher des recettes...",
    "All Categories": "Toutes les catégories",
    Breakfast: "Petit-déjeuner",
    Lunch: "Déjeuner",
    Dinner: "Dîner",
    Dessert: "Dessert",
    "View Recipe": "Voir la recette",
    "Edit Recipe": "Modifier la recette",
    "Update Recipe": "Mettre à jour la recette",
    "Add a Recipe": "Ajouter une recette",
    Title: "Titre",
    Description: "Description",
    Ingredients: "Ingrédients",
    Steps: "Étapes",
    Category: "Catégorie",
    "Recipe Image (optional)": "Image de la recette (facultatif)",
    Comments: "Commentaires",
    "Post Comment": "Publier un commentaire",
    "Add a comment...": "Ajouter un commentaire...",
    "Please log in to view your profile.":
      "Veuillez vous connecter pour voir votre profil.",
    "Admin Panel - Manage Recipes":
      "Panneau d'administration - Gérer les recettes",
    Email: "Email",
    Password: "Mot de passe",
    "Invalid email or password.": "Email ou mot de passe invalide.",
    "Failed to register. Try again.": "Échec de l'inscription. Réessayez.",
    "Repeat Password": "Répéter le mot de passe",
    "Repeat your password": "Répétez votre mot de passe",
    "Passwords do not match.": "Les mots de passe ne correspondent pas.",
    "Enter your email": "Entrez votre email",
    "Enter your password": "Entrez votre mot de passe",
    "Recipe title": "Titre de la recette",
    "Recipe description": "Description de la recette",
    "Recipe ingredients": "Ingrédients de la recette",
    "Recipe steps": "Étapes de la recette",
    "Recipe category": "Catégorie de la recette",
    "Recipe image": "Image de la recette",
    "Recipe comments": "Commentaires de la recette",
    "Post a comment": "Publier un commentaire",
    "Add a comment": "Ajouter un commentaire",
    "Describe your recipe": "Décrivez votre recette",
    "List ingredients, one per line": "Listez les ingrédients, un par ligne",
    "List steps, one per line": "Listez les étapes, une par ligne",
    "Select a category": "Sélectionnez une catégorie",
    Previous: "Précédent",
    Next: "Suivant",
    "No recipes found.": "Aucune recette trouvée.",
    "No comments yet.": "Aucun commentaire pour l'instant.",
    "Recipe App": "Plateforme de partage de recettes",
    "Update your recipe details.":
      "Mettez à jour les détails de votre recette.",
    "Share your favorite recipe with the world!":
      "Partagez votre recette préférée avec le monde !",
    "Discover and share amazing recipes!":
      "Découvrez et partagez des recettes incroyables !",
    "Log in to access your recipes!":
      "Connectez-vous pour accéder à vos recettes !",
    "Manage all recipes as an admin.":
      "Gérez toutes les recettes en tant qu'administrateur.",
    "View your personal recipe collection!":
      "Consultez votre collection personnelle de recettes !",
    "Create an account to share your recipes!":
      "Créez un compte pour partager vos recettes !",
    "Related Recipes": "Recettes similaires",
    "Recipe not found.": "Recette non trouvée.",
    "404 - Page Not Found": "404 - Page non trouvée",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Désolé, la page que vous cherchez n'existe pas ou a été déplacée.",
    "Back to Home": "Retour à l'accueil",
    "Sort by...": "Trier par...",
    "Alphabetical (A-Z)": "Alphabétique (A-Z)",
    "Alphabetical (Z-A)": "Alphabétique (Z-A)",
    "Date (Oldest First)": "Date (Plus ancien en premier)",
    "Date (Newest First)": "Date (Plus récent en premier)",
    "Register with Google": "S'inscrire avec Google",
    "Login with Google": "Se connecter avec Google",
    "Failed to register with Google. Try again.":
      "Échec de l'inscription avec Google. Réessayez.",
    "Failed to login with Google. Try again.":
      "Échec de la connexion avec Google. Réessayez.",
    Instructions: "Instructions",
    "Privacy Policy": "Politique de confidentialité",
    "YouTube Video URL (optional)": "URL de la vidéo YouTube (facultatif)",
    "Invalid YouTube URL": "URL YouTube invalide",
    "Video Tutorial": "Tutoriel vidéo",
    Username: "Nom d'utilisateur",
    "Enter your username": "Entrez votre nom d'utilisateur",
    "Account Settings": "Paramètres du compte",
    "Current Password": "Mot de passe actuel",
    "Enter your current password": "Entrez votre mot de passe actuel",
    "New Password": "Nouveau mot de passe",
    "Enter your new password": "Entrez votre nouveau mot de passe",
    "Confirm New Password": "Confirmer le nouveau mot de passe",
    "Repeat your new password": "Répétez votre nouveau mot de passe",
    "Update Password": "Mettre à jour le mot de passe",
    "Delete Account": "Supprimer le compte",
    "Confirm Account Deletion": "Confirmer la suppression du compte",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible et toutes vos recettes seront supprimées.",
    Cancel: "Annuler",
    "My Profile": "Mon profil",
    "Update Username": "Mettre à jour le nom d'utilisateur",
    "Username updated successfully.":
      "Nom d'utilisateur mis à jour avec succès.",
    "Failed to update username. Try again.":
      "Échec de la mise à jour du nom d'utilisateur. Réessayez.",
    "Password updated successfully.": "Mot de passe mis à jour avec succès.",
    "Failed to update password. Check your current password.":
      "Échec de la mise à jour du mot de passe. Vérifiez votre mot de passe actuel.",
    "Account deleted successfully.": "Compte supprimé avec succès.",
    "Failed to delete account. Check your current password.":
      "Échec de la suppression du compte. Vérifiez votre mot de passe actuel.",
    "Manage your account and view your recipes!":
      "Gérez votre compte et consultez vos recettes !",
    "Failed to register: ": "Échec de l'inscription : ",
    "Failed to register with Google: ": "Échec de l'inscription avec Google : ",
    "Invalid email or password: ": "Email ou mot de passe invalide : ",
    "Failed to login with Google: ": "Échec de la connexion avec Google : ",
    "Username must be 20 characters or less.":
      "Le nom d'utilisateur doit comporter 20 caractères ou moins.",
    "Session expired. Please log in again.":
      "Session expirée. Veuillez vous reconnecter.",
    "Error updating password:":
      "Erreur lors de la mise à jour du mot de passe :",
    "The current password is incorrect.":
      "Le mot de passe actuel est incorrect.",
    "Too many attempts. Please try again later.":
      "Trop de tentatives. Veuillez réessayer plus tard.",
    "Password should be at least 6 characters.":
      "Le mot de passe doit comporter au moins 6 caractères.",
    "Failed to update password: ": "Échec de la mise à jour du mot de passe : ",
    "Please log in to add a comment.":
      "Veuillez vous connecter pour ajouter un commentaire.",
    "Invalid email or password": "Email ou mot de passe invalide",
    Author: "Auteur",
  },
  es: {
    Home: "Inicio",
    "Add Recipe": "Añadir receta",
    Profile: "Perfil",
    Admin: "Admin",
    Logout: "Cerrar sesión",
    Login: "Iniciar sesión",
    Register: "Registrarse",
    "Recipe Sharing": "Compartir recetas",
    "My Recipes": "Mis recetas",
    View: "Ver",
    Edit: "Editar",
    Delete: "Eliminar",
    "Explore Recipes": "Explorar recetas",
    "Search recipes...": "Buscar recetas...",
    "All Categories": "Todas las categorías",
    Breakfast: "Desayuno",
    Lunch: "Almuerzo",
    Dinner: "Cena",
    Dessert: "Postre",
    "View Recipe": "Ver receta",
    "Edit Recipe": "Editar receta",
    "Update Recipe": "Actualizar receta",
    "Add a Recipe": "Añadir una receta",
    Title: "Título",
    Description: "Descripción",
    Ingredients: "Ingredientes",
    Steps: "Pasos",
    Category: "Categoría",
    "Recipe Image (optional)": "Imagen de la receta (opcional)",
    Comments: "Comentarios",
    "Post Comment": "Publicar comentario",
    "Add a comment...": "Añadir un comentario...",
    "Please log in to view your profile.":
      "Por favor, inicia sesión para ver tu perfil.",
    "Admin Panel - Manage Recipes":
      "Panel de administración - Gestionar recetas",
    Email: "Correo electrónico",
    Password: "Contraseña",
    "Invalid email or password.": "Correo electrónico o contraseña inválidos.",
    "Failed to register. Try again.": "No se pudo registrar. Intenta de nuevo.",
    "Repeat Password": "Repetir contraseña",
    "Repeat your password": "Repite tu contraseña",
    "Passwords do not match.": "Las contraseñas no coinciden.",
    "Enter your email": "Ingresa tu correo electrónico",
    "Enter your password": "Ingresa tu contraseña",
    "Recipe title": "Título de la receta",
    "Recipe description": "Descripción de la receta",
    "Recipe ingredients": "Ingredientes de la receta",
    "Recipe steps": "Pasos de la receta",
    "Recipe category": "Categoría de la receta",
    "Recipe image": "Imagen de la receta",
    "Recipe comments": "Comentarios de la receta",
    "Post a comment": "Publicar un comentario",
    "Add a comment": "Añadir un comentario",
    "Describe your recipe": "Describe tu receta",
    "List ingredients, one per line": "Lista los ingredientes, uno por línea",
    "List steps, one per line": "Lista los pasos, uno por línea",
    "Select a category": "Selecciona una categoría",
    Previous: "Anterior",
    Next: "Siguiente",
    "No recipes found.": "No se encontraron recetas.",
    "No comments yet.": "Aún no hay comentarios.",
    "Recipe App": "Plataforma de recetas",
    "Update your recipe details.": "Actualiza los detalles de tu receta.",
    "Share your favorite recipe with the world!":
      "¡Comparte tu receta favorita con el mundo!",
    "Discover and share amazing recipes!":
      "¡Descubre y comparte recetas increíbles!",
    "Log in to access your recipes!":
      "¡Inicia sesión para acceder a tus recetas!",
    "Manage all recipes as an admin.":
      "Gestiona todas las recetas como administrador.",
    "View your personal recipe collection!":
      "¡Ve tu colección personal de recetas!",
    "Create an account to share your recipes!":
      "¡Crea una cuenta para compartir tus recetas!",
    "Related Recipes": "Recetas relacionadas",
    "Recipe not found.": "Receta no encontrada.",
    "404 - Page Not Found": "404 - Página no encontrada",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Lo sentimos, la página que buscas no existe o ha sido movida.",
    "Back to Home": "Volver al inicio",
    "Sort by...": "Ordenar por...",
    "Alphabetical (A-Z)": "Alfabético (A-Z)",
    "Alphabetical (Z-A)": "Alfabético (Z-A)",
    "Date (Oldest First)": "Fecha (Más antiguo primero)",
    "Date (Newest First)": "Fecha (Más reciente primero)",
    "Register with Google": "Registrarse con Google",
    "Login with Google": "Iniciar sesión con Google",
    "Failed to register with Google. Try again.":
      "No se pudo registrar con Google. Intenta de nuevo.",
    "Failed to login with Google. Try again.":
      "No se pudo iniciar sesión con Google. Intenta de nuevo.",
    Instructions: "Instrucciones",
    "Privacy Policy": "Política de privacidad",
    "YouTube Video URL (optional)": "URL del video de YouTube (opcional)",
    "Invalid YouTube URL": "URL de YouTube no válida",
    "Video Tutorial": "Tutorial en video",
    Username: "Nombre de usuario",
    "Enter your username": "Ingresa tu nombre de usuario",
    "Account Settings": "Configuración de la cuenta",
    "Current Password": "Contraseña actual",
    "Enter your current password": "Ingresa tu contraseña actual",
    "New Password": "Nueva contraseña",
    "Enter your new password": "Ingresa tu nueva contraseña",
    "Confirm New Password": "Confirmar nueva contraseña",
    "Repeat your new password": "Repite tu nueva contraseña",
    "Update Password": "Actualizar contraseña",
    "Delete Account": "Eliminar cuenta",
    "Confirm Account Deletion": "Confirmar eliminación de cuenta",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "¿Estás seguro de que deseas eliminar tu cuenta? Esta acción no se puede deshacer y todas tus recetas serán eliminadas.",
    Cancel: "Cancelar",
    "My Profile": "Mi perfil",
    "Update Username": "Actualizar nombre de usuario",
    "Username updated successfully.":
      "Nombre de usuario actualizado con éxito.",
    "Failed to update username. Try again.":
      "No se pudo actualizar el nombre de usuario. Intenta de nuevo.",
    "Password updated successfully.": "Contraseña actualizada con éxito.",
    "Failed to update password. Check your current password.":
      "No se pudo actualizar la contraseña. Verifica tu contraseña actual.",
    "Account deleted successfully.": "Cuenta eliminada con éxito.",
    "Failed to delete account. Check your current password.":
      "No se pudo eliminar la cuenta. Verifica tu contraseña actual.",
    "Manage your account and view your recipes!":
      "¡Gestiona tu cuenta y ve tus recetas!",
    "Failed to register: ": "No se pudo registrar: ",
    "Failed to register with Google: ": "No se pudo registrar con Google: ",
    "Invalid email or password: ":
      "Correo electrónico o contraseña inválidos: ",
    "Failed to login with Google: ": "No se pudo iniciar sesión con Google: ",
    "Username must be 20 characters or less.":
      "El nombre de usuario debe tener 20 caracteres o menos.",
    "Session expired. Please log in again.":
      "Sessão expirada. Por favor, faça login novamente.",
    "Error updating password:": "Erro ao atualizar a senha:",
    "The current password is incorrect.": "A senha atual está incorreta.",
    "Too many attempts. Please try again later.":
      "Muitas tentativas. Por favor, tente novamente mais tarde.",
    "Password should be at least 6 characters.":
      "A senha deve ter pelo menos 6 caracteres.",
    "Failed to update password: ": "Falha ao atualizar a senha: ",
    "Please log in to add a comment.":
      "Por favor, inicia sesión para añadir un comentario.",
    "Invalid email or password": "Correo electrónico o contraseña inválidos",
    Author: "Autor",
  },
  pt: {
    Home: "Início",
    "Add Recipe": "Adicionar receita",
    Profile: "Perfil",
    Admin: "Admin",
    Logout: "Sair",
    Login: "Entrar",
    Register: "Registrar",
    "Recipe Sharing": "Compartilhamento de receitas",
    "My Recipes": "Minhas receitas",
    View: "Ver",
    Edit: "Editar",
    Delete: "Excluir",
    "Explore Recipes": "Explorar receitas",
    "Search recipes...": "Pesquisar receitas...",
    "All Categories": "Todas as categorias",
    Breakfast: "Café da manhã",
    Lunch: "Almoço",
    Dinner: "Jantar",
    Dessert: "Sobremesa",
    "View Recipe": "Ver receita",
    "Edit Recipe": "Editar receita",
    "Update Recipe": "Atualizar receita",
    "Add a Recipe": "Adicionar uma receita",
    Title: "Título",
    Description: "Descrição",
    Ingredients: "Ingredientes",
    Steps: "Passos",
    Category: "Categoria",
    "Recipe Image (optional)": "Imagem da receita (opcional)",
    Comments: "Comentários",
    "Post Comment": "Publicar comentário",
    "Add a comment...": "Adicionar um comentário...",
    "Please log in to view your profile.":
      "Por favor, faça login para ver seu perfil.",
    "Admin Panel - Manage Recipes":
      "Painel de administração - Gerenciar receitas",
    Email: "E-mail",
    Password: "Senha",
    "Invalid email or password.": "E-mail ou senha inválidos.",
    "Failed to register. Try again.": "Falha ao registrar. Tente novamente.",
    "Repeat Password": "Repetir senha",
    "Repeat your password": "Repita sua senha",
    "Passwords do not match.": "As senhas não coincidem.",
    "Enter your email": "Digite seu e-mail",
    "Enter your password": "Digite sua senha",
    "Recipe title": "Título da receita",
    "Recipe description": "Descrição da receita",
    "Recipe ingredients": "Ingredientes da receita",
    "Recipe steps": "Passos da receita",
    "Recipe category": "Categoria da receita",
    "Recipe image": "Imagem da receita",
    "Recipe comments": "Comentários da receita",
    "Post a comment": "Publicar um comentário",
    "Add a comment": "Adicionar um comentário",
    "Describe your recipe": "Descreva sua receita",
    "List ingredients, one per line": "Liste os ingredientes, um por linha",
    "List steps, one per line": "Liste os passos, um por linha",
    "Select a category": "Selecione uma categoria",
    Previous: "Anterior",
    Next: "Próximo",
    "No recipes found.": "Nenhuma receita encontrada.",
    "No comments yet.": "Ainda não há comentários.",
    "Recipe App": "Plataforma de receitas",
    "Update your recipe details.": "Atualize os detalhes da sua receita.",
    "Share your favorite recipe with the world!":
      "Compartilhe sua receita favorita com o mundo!",
    "Discover and share amazing recipes!":
      "Descubra e compartilhe receitas incríveis!",
    "Log in to access your recipes!": "Faça login para acessar suas receitas!",
    "Manage all recipes as an admin.":
      "Gerencie todas as receitas como administrador.",
    "View your personal recipe collection!":
      "Veja sua coleção pessoal de receitas!",
    "Create an account to share your recipes!":
      "Crie uma conta para compartilhar suas receitas!",
    "Related Recipes": "Receitas relacionadas",
    "Recipe not found.": "Receita não encontrada.",
    "404 - Page Not Found": "404 - Página não encontrada",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Desculpe, a página que você está procurando não existe ou foi movida.",
    "Back to Home": "Voltar ao início",
    "Sort by...": "Ordenar por...",
    "Alphabetical (A-Z)": "Alfabético (A-Z)",
    "Alphabetical (Z-A)": "Alfabético (Z-A)",
    "Date (Oldest First)": "Data (Mais antigo primeiro)",
    "Date (Newest First)": "Data (Mais recente primeiro)",
    "Register with Google": "Registrar com Google",
    "Login with Google": "Entrar com Google",
    "Failed to register with Google. Try again.":
      "Falha ao registrar com Google. Tente novamente.",
    "Failed to login with Google. Try again.":
      "Falha ao entrar com Google. Tente novamente.",
    Instructions: "Instruções",
    "Privacy Policy": "Política de Privacidade",
    "YouTube Video URL (optional)": "URL do vídeo do YouTube (opcional)",
    "Invalid YouTube URL": "URL do YouTube inválido",
    "Video Tutorial": "Tutorial em vídeo",
    Username: "Nome de usuário",
    "Enter your username": "Digite seu nome de usuário",
    "Account Settings": "Configurações da conta",
    "Current Password": "Senha atual",
    "Enter your current password": "Digite sua senha atual",
    "New Password": "Nova senha",
    "Enter your new password": "Digite sua nova senha",
    "Confirm New Password": "Confirmar nova senha",
    "Repeat your new password": "Repita sua nova senha",
    "Update Password": "Atualizar senha",
    "Delete Account": "Excluir conta",
    "Confirm Account Deletion": "Confirmar exclusão da conta",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "Você tem certeza de que deseja excluir sua conta? Esta ação não pode ser desfeita e todas as suas receitas serão excluídas.",
    Cancel: "Cancelar",
    "My Profile": "Meu perfil",
    "Update Username": "Atualizar nome de usuário",
    "Username updated successfully.": "Nome de usuário atualizado com sucesso.",
    "Failed to update username. Try again.":
      "Falha ao atualizar nome de usuário. Tente novamente.",
    "Password updated successfully.": "Senha atualizada com sucesso.",
    "Failed to update password. Check your current password.":
      "Falha ao atualizar senha. Verifique sua senha atual.",
    "Account deleted successfully.": "Conta excluída com sucesso.",
    "Failed to delete account. Check your current password.":
      "Falha ao excluir conta. Verifique sua senha atual.",
    "Manage your account and view your recipes!":
      "Gerencie sua conta e veja suas receitas!",
    "Failed to register: ": "Falha ao registrar: ",
    "Failed to register with Google: ": "Falha ao registrar com Google: ",
    "Invalid email or password: ": "E-mail ou senha inválidos: ",
    "Failed to login with Google: ": "Falha ao entrar com Google: ",
    "Username must be 20 characters or less.":
      "O nome de usuário deve ter 20 caracteres ou menos.",
    "Session expired. Please log in again.":
      "Sessão expirada. Por favor, faça login novamente.",
    "Error updating password:": "Erro ao atualizar a senha:",
    "The current password is incorrect.": "A senha atual está incorreta.",
    "Too many attempts. Please try again later.":
      "Muitas tentativas. Por favor, tente novamente mais tarde.",
    "Password should be at least 6 characters.":
      "A senha deve ter pelo menos 6 caracteres.",
    "Failed to update password: ": "Falha ao atualizar a senha: ",
    "Please log in to add a comment.":
      "Por favor, faça login para adicionar um comentário.",
    "Invalid email or password": "E-mail ou senha inválidos",
    Author: "Autor",
  },
  de: {
    Home: "Startseite",
    "Add Recipe": "Rezept hinzufügen",
    Profile: "Profil",
    Admin: "Admin",
    Logout: "Abmelden",
    Login: "Anmelden",
    Register: "Registrieren",
    "Recipe Sharing": "Rezeptfreigabe",
    "My Recipes": "Meine Rezepte",
    View: "Ansehen",
    Edit: "Bearbeiten",
    Delete: "Löschen",
    "Explore Recipes": "Rezepte erkunden",
    "Search recipes...": "Rezepte suchen...",
    "All Categories": "Alle Kategorien",
    Breakfast: "Frühstück",
    Lunch: "Mittagessen",
    Dinner: "Abendessen",
    Dessert: "Dessert",
    "View Recipe": "Rezept ansehen",
    "Edit Recipe": "Rezept bearbeiten",
    "Update Recipe": "Rezept aktualisieren",
    "Add a Recipe": "Ein Rezept hinzufügen",
    Title: "Titel",
    Description: "Beschreibung",
    Ingredients: "Zutaten",
    Steps: "Schritte",
    Category: "Kategorie",
    "Recipe Image (optional)": "Rezeptbild (optional)",
    Comments: "Kommentare",
    "Post Comment": "Kommentar veröffentlichen",
    "Add a comment...": "Einen Kommentar hinzufügen...",
    "Please log in to view your profile.":
      "Bitte melde dich an, um dein Profil zu sehen.",
    "Admin Panel - Manage Recipes": "Admin-Panel - Rezepte verwalten",
    Email: "E-Mail",
    Password: "Passwort",
    "Invalid email or password.": "Ungültige E-Mail oder Passwort.",
    "Failed to register. Try again.":
      "Registrierung fehlgeschlagen. Versuche es erneut.",
    "Repeat Password": "Passwort wiederholen",
    "Repeat your password": "Wiederhole dein Passwort",
    "Passwords do not match.": "Die Passwörter stimmen nicht überein.",
    "Enter your email": "Gib deine E-Mail ein",
    "Enter your password": "Gib dein Passwort ein",
    "Recipe title": "Rezepttitel",
    "Recipe description": "Rezeptbeschreibung",
    "Recipe ingredients": "Rezeptzutaten",
    "Recipe steps": "Rezeptschritte",
    "Recipe category": "Rezeptkategorie",
    "Recipe image": "Rezeptbild",
    "Recipe comments": "Rezeptkommentare",
    "Post a comment": "Einen Kommentar veröffentlichen",
    "Add a comment": "Einen Kommentar hinzufügen",
    "Describe your recipe": "Beschreibe dein Rezept",
    "List ingredients, one per line": "Liste die Zutaten auf, eine pro Zeile",
    "List steps, one per line": "Liste die Schritte auf, einen pro Zeile",
    "Select a category": "Wähle eine Kategorie",
    Previous: "Vorherige",
    Next: "Nächste",
    "No recipes found.": "Keine Rezepte gefunden.",
    "No comments yet.": "Noch keine Kommentare.",
    "Recipe App": "Rezeptplattform",
    "Update your recipe details.": "Aktualisiere die Details deines Rezepts.",
    "Share your favorite recipe with the world!":
      "Teile dein Lieblingsrezept mit der Welt!",
    "Discover and share amazing recipes!": "Entdecke und teile tolle Rezepte!",
    "Log in to access your recipes!":
      "Melde dich an, um auf deine Rezepte zuzugreifen!",
    "Manage all recipes as an admin.":
      "Verwalte alle Rezepte als Administrator.",
    "View your personal recipe collection!":
      "Sieh dir deine persönliche Rezeptsammlung an!",
    "Create an account to share your recipes!":
      "Erstelle ein Konto, um deine Rezepte zu teilen!",
    "Related Recipes": "Ähnliche Rezepte",
    "Recipe not found.": "Rezept nicht gefunden.",
    "404 - Page Not Found": "404 - Seite nicht gefunden",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Entschuldigung, die Seite, die du suchst, existiert nicht oder wurde verschoben.",
    "Back to Home": "Zurück zur Startseite",
    "Sort by...": "Sortieren nach...",
    "Alphabetical (A-Z)": "Alphabetisch (A-Z)",
    "Alphabetical (Z-A)": "Alphabetisch (Z-A)",
    "Date (Oldest First)": "Datum (Älteste zuerst)",
    "Date (Newest First)": "Datum (Neueste zuerst)",
    "Register with Google": "Mit Google registrieren",
    "Login with Google": "Mit Google anmelden",
    "Failed to register with Google. Try again.":
      "Registrierung mit Google fehlgeschlagen. Versuche es erneut.",
    "Failed to login with Google. Try again.":
      "Anmeldung mit Google fehlgeschlagen. Versuche es erneut.",
    Instructions: "Anleitung",
    "Privacy Policy": "Datenschutz",
    "YouTube Video URL (optional)": "YouTube-Video-URL (optional)",
    "Invalid YouTube URL": "Ungültige YouTube-URL",
    "Video Tutorial": "Videoanleitung",
    Username: "Benutzername",
    "Enter your username": "Gib deinen Benutzernamen ein",
    "Account Settings": "Kontoeinstellungen",
    "Current Password": "Aktuelles Passwort",
    "Enter your current password": "Gib dein aktuelles Passwort ein",
    "New Password": "Neues Passwort",
    "Enter your new password": "Gib dein neues Passwort ein",
    "Confirm New Password": "Neues Passwort bestätigen",
    "Repeat your new password": "Wiederhole dein neues Passwort",
    "Update Password": "Passwort aktualisieren",
    "Delete Account": "Konto löschen",
    "Confirm Account Deletion": "Kontolöschung bestätigen",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "Bist du sicher, dass du dein Konto löschen möchtest? Diese Aktion kann nicht rückgängig gemacht werden, und alle deine Rezepte werden gelöscht.",
    Cancel: "Abbrechen",
    "My Profile": "Mein Profil",
    "Update Username": "Benutzernamen aktualisieren",
    "Username updated successfully.": "Benutzername erfolgreich aktualisiert.",
    "Failed to update username. Try again.":
      "Fehler beim Aktualisieren des Benutzernamens. Versuche es erneut.",
    "Password updated successfully.": "Passwort erfolgreich aktualisiert.",
    "Failed to update password. Check your current password.":
      "Fehler beim Aktualisieren des Passworts. Überprüfe dein aktuelles Passwort.",
    "Account deleted successfully.": "Konto erfolgreich gelöscht.",
    "Failed to delete account. Check your current password.":
      "Fehler beim Löschen des Kontos. Überprüfe dein aktuelles Passwort.",
    "Manage your account and view your recipes!":
      "Verwalte dein Konto und sieh dir deine Rezepte an!",
    "Failed to register: ": "Registrierung fehlgeschlagen: ",
    "Failed to register with Google: ":
      "Registrierung mit Google fehlgeschlagen: ",
    "Invalid email or password: ": "Ungültige E-Mail oder Passwort: ",
    "Failed to login with Google: ": "Anmeldung mit Google fehlgeschlagen: ",
    "Username must be 20 characters or less.":
      "Der Benutzername darf maximal 20 Zeichen lang sein.",
    "Session expired. Please log in again.":
      "Sitzung abgelaufen. Bitte melden Sie sich erneut an.",
    "Error updating password:": "Fehler beim Aktualisieren des Passworts:",
    "The current password is incorrect.": "Das aktuelle Passwort ist falsch.",
    "Too many attempts. Please try again later.":
      "Zu viele Versuche. Bitte versuchen Sie es später erneut.",
    "Password should be at least 6 characters.":
      "Das Passwort sollte mindestens 6 Zeichen lang sein.",
    "Failed to update password: ": "Fehler beim Aktualisieren des Passworts: ",
    "Please log in to add a comment.":
      "Bitte melde dich an, um einen Kommentar hinzuzufügen.",
    "Invalid email or password": "Ungültige E-Mail oder Passwort",
    Author: "Autor",
  },
  it: {
    Home: "Home",
    "Add Recipe": "Aggiungi ricetta",
    Profile: "Profilo",
    Admin: "Admin",
    Logout: "Esci",
    Login: "Accedi",
    Register: "Registrati",
    "Recipe Sharing": "Condivisione di ricette",
    "My Recipes": "Le mie ricette",
    View: "Visualizza",
    Edit: "Modifica",
    Delete: "Elimina",
    "Explore Recipes": "Esplora ricette",
    "Search recipes...": "Cerca ricette...",
    "All Categories": "Tutte le categorie",
    Breakfast: "Colazione",
    Lunch: "Pranzo",
    Dinner: "Cena",
    Dessert: "Dessert",
    "View Recipe": "Visualizza ricetta",
    "Edit Recipe": "Modifica ricetta",
    "Update Recipe": "Aggiorna ricetta",
    "Add a Recipe": "Aggiungi una ricetta",
    Title: "Titolo",
    Description: "Descrizione",
    Ingredients: "Ingredienti",
    Steps: "Passaggi",
    Category: "Categoria",
    "Recipe Image (optional)": "Immagine della ricetta (opzionale)",
    Comments: "Commenti",
    "Post Comment": "Pubblica commento",
    "Add a comment...": "Aggiungi un commento...",
    "Please log in to view your profile.":
      "Accedi per visualizzare il tuo profilo.",
    "Admin Panel - Manage Recipes":
      "Pannello di amministrazione - Gestisci ricette",
    Email: "Email",
    Password: "Password",
    "Invalid email or password.": "Email o password non valide.",
    "Failed to register. Try again.": "Registrazione fallita. Riprova.",
    "Repeat Password": "Ripeti password",
    "Repeat your password": "Ripeti la tua password",
    "Passwords do not match.": "Le password non corrispondono.",
    "Enter your email": "Inserisci la tua email",
    "Enter your password": "Inserisci la tua password",
    "Recipe title": "Titolo della ricetta",
    "Recipe description": "Descrizione della ricetta",
    "Recipe ingredients": "Ingredienti della ricetta",
    "Recipe steps": "Passaggi della ricetta",
    "Recipe category": "Categoria della ricetta",
    "Recipe image": "Immagine della ricetta",
    "Recipe comments": "Commenti della ricetta",
    "Post a comment": "Pubblica un commento",
    "Add a comment": "Aggiungi un commento",
    "Describe your recipe": "Descrivi la tua ricetta",
    "List ingredients, one per line": "Elenca gli ingredienti, uno per riga",
    "List steps, one per line": "Elenca i passaggi, uno per riga",
    "Select a category": "Seleziona una categoria",
    Previous: "Precedente",
    Next: "Successivo",
    "No recipes found.": "Nessuna ricetta trovata.",
    "No comments yet.": "Nessun commento finora.",
    "Recipe App": "Piattaforma di condivisione ricette",
    "Update your recipe details.": "Aggiorna i dettagli della tua ricetta.",
    "Share your favorite recipe with the world!":
      "Condividi la tua ricetta preferita con il mondo!",
    "Discover and share amazing recipes!":
      "Scopri e condividi ricette fantastiche!",
    "Log in to access your recipes!": "Accedi per accedere alle tue ricette!",
    "Manage all recipes as an admin.":
      "Gestisci tutte le ricette come amministratore.",
    "View your personal recipe collection!":
      "Visualizza la tua collezione personale di ricette!",
    "Create an account to share your recipes!":
      "Crea un account per condividere le tue ricette!",
    "Related Recipes": "Ricette correlate",
    "Recipe not found.": "Ricetta non trovata.",
    "404 - Page Not Found": "404 - Pagina non trovata",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Spiacenti, la pagina che stai cercando non esiste o è stata spostata.",
    "Back to Home": "Torna alla Home",
    "Sort by...": "Ordina per...",
    "Alphabetical (A-Z)": "Alfabetico (A-Z)",
    "Alphabetical (Z-A)": "Alfabetico (Z-A)",
    "Date (Oldest First)": "Data (dal più vecchio)",
    "Date (Newest First)": "Data (dal più recente)",
    "Register with Google": "Registrati con Google",
    "Login with Google": "Accedi con Google",
    "Failed to register with Google. Try again.":
      "Registrazione con Google fallita. Riprova.",
    "Failed to login with Google. Try again.":
      "Accesso con Google fallito. Riprova.",
    Instructions: "Istruzioni",
    "Privacy Policy": "Informativa sulla privacy",
    "YouTube Video URL (optional)": "URL video di YouTube (opzionale)",
    "Invalid YouTube URL": "URL di YouTube non valido",
    "Video Tutorial": "Video tutorial",
    Username: "Nome utente",
    "Enter your username": "Inserisci il tuo nome utente",
    "Account Settings": "Impostazioni dell'account",
    "Current Password": "Password attuale",
    "Enter your current password": "Inserisci la tua password attuale",
    "New Password": "Nuova password",
    "Enter your new password": "Inserisci la tua nuova password",
    "Confirm New Password": "Conferma nuova password",
    "Repeat your new password": "Ripeti la tua nuova password",
    "Update Password": "Aggiorna password",
    "Delete Account": "Elimina account",
    "Confirm Account Deletion": "Conferma eliminazione account",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "Sei sicuro di voler eliminare il tuo account? Questa azione non può essere annullata e tutte le tue ricette verranno eliminate.",
    Cancel: "Annulla",
    "My Profile": "Il mio profilo",
    "Update Username": "Aggiorna nome utente",
    "Username updated successfully.": "Nome utente aggiornato con successo.",
    "Failed to update username. Try again.":
      "Aggiornamento nome utente fallito. Riprova.",
    "Password updated successfully.": "Password aggiornata con successo.",
    "Failed to update password. Check your current password.":
      "Aggiornamento password fallito. Controlla la tua password attuale.",
    "Account deleted successfully.": "Account eliminato con successo.",
    "Failed to delete account. Check your current password.":
      "Eliminazione account fallita. Controlla la tua password attuale.",
    "Manage your account and view your recipes!":
      "Gestisci il tuo account e visualizza le tue ricette!",
    "Failed to register: ": "Registrazione fallita: ",
    "Failed to register with Google: ": "Registrazione con Google fallita: ",
    "Invalid email or password: ": "Email o password non valide: ",
    "Failed to login with Google: ": "Accesso con Google fallito: ",
    "Username must be 20 characters or less.":
      "Il nome utente deve essere di 20 caratteri o meno.",
    "Session expired. Please log in again.":
      "Sessione scaduta. Per favore, accedi di nuovo.",
    "Error updating password:":
      "Errore durante l'aggiornamento della password:",
    "The current password is incorrect.": "La password attuale è errata.",
    "Too many attempts. Please try again later.":
      "Troppi tentativi. Riprova più tardi.",
    "Password should be at least 6 characters.":
      "La password deve essere di almeno 6 caratteri.",
    "Failed to update password: ": "Aggiornamento della password fallito: ",
    "Please log in to add a comment.": "Accedi per aggiungere un commento.",
    "Invalid email or password": "Email o password non valide",
    Author: "Autore",
  },
  ru: {
    Home: "Главная",
    "Add Recipe": "Добавить рецепт",
    Profile: "Профиль",
    Admin: "Админ",
    Logout: "Выйти",
    Login: "Войти",
    Register: "Зарегистрироваться",
    "Recipe Sharing": "Обмен рецептами",
    "My Recipes": "Мои рецепты",
    View: "Просмотр",
    Edit: "Редактировать",
    Delete: "Удалить",
    "Explore Recipes": "Исследовать рецепты",
    "Search recipes...": "Поиск рецептов...",
    "All Categories": "Все категории",
    Breakfast: "Завтрак",
    Lunch: "Обед",
    Dinner: "Ужин",
    Dessert: "Десерт",
    "View Recipe": "Просмотреть рецепт",
    "Edit Recipe": "Редактировать рецепт",
    "Update Recipe": "Обновить рецепт",
    "Add a Recipe": "Добавить рецепт",
    Title: "Название",
    Description: "Описание",
    Ingredients: "Ингредиенты",
    Steps: "Шаги",
    Category: "Категория",
    "Recipe Image (optional)": "Изображение рецепта (опционально)",
    Comments: "Комментарии",
    "Post Comment": "Опубликовать комментарий",
    "Add a comment...": "Добавить комментарий...",
    "Please log in to view your profile.":
      "Пожалуйста, войдите, чтобы просмотреть свой профиль.",
    "Admin Panel - Manage Recipes":
      "Панель администратора - Управление рецептами",
    Email: "Электронная почта",
    Password: "Пароль",
    "Invalid email or password.":
      "Неверный адрес электронной почты или пароль.",
    "Failed to register. Try again.":
      "Не удалось зарегистрироваться. Попробуйте еще раз.",
    "Repeat Password": "Повторите пароль",
    "Repeat your password": "Повторите ваш пароль",
    "Passwords do not match.": "Пароли не совпадают.",
    "Enter your email": "Введите ваш email",
    "Enter your password": "Введите ваш пароль",
    "Recipe title": "Название рецепта",
    "Recipe description": "Описание рецепта",
    "Recipe ingredients": "Ингредиенты рецепта",
    "Recipe steps": "Шаги рецепта",
    "Recipe category": "Категория рецепта",
    "Recipe image": "Изображение рецепта",
    "Recipe comments": "Комментарии к рецепту",
    "Post a comment": "Опубликовать комментарий",
    "Add a comment": "Добавить комментарий",
    "Describe your recipe": "Опишите ваш рецепт",
    "List ingredients, one per line":
      "Перечислите ингредиенты, по одному в строке",
    "List steps, one per line": "Перечислите шаги, по одному в строке",
    "Select a category": "Выберите категорию",
    Previous: "Предыдущий",
    Next: "Следующий",
    "No recipes found.": "Рецепты не найдены.",
    "No comments yet.": "Комментариев пока нет.",
    "Recipe App": "Платформа обмена рецептами",
    "Update your recipe details.": "Обновите детали вашего рецепта.",
    "Share your favorite recipe with the world!":
      "Поделитесь своим любимым рецептом с миром!",
    "Discover and share amazing recipes!":
      "Откройте и поделитесь удивительными рецептами!",
    "Log in to access your recipes!":
      "Войдите, чтобы получить доступ к вашим рецептам!",
    "Manage all recipes as an admin.":
      "Управляйте всеми рецептами как администратор.",
    "View your personal recipe collection!":
      "Просмотрите вашу личную коллекцию рецептов!",
    "Create an account to share your recipes!":
      "Создайте аккаунт, чтобы делиться своими рецептами!",
    "Related Recipes": "Похожие рецепты",
    "Recipe not found.": "Рецепт не найден.",
    "404 - Page Not Found": "404 - Страница не найдена",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "Извините, страница, которую вы ищете, не существует или была перемещена.",
    "Back to Home": "Вернуться на главную",
    "Sort by...": "Сортировать по...",
    "Alphabetical (A-Z)": "По алфавиту (A-Я)",
    "Alphabetical (Z-A)": "По алфавиту (Я-A)",
    "Date (Oldest First)": "Дата (сначала старые)",
    "Date (Newest First)": "Дата (сначала новые)",
    "Register with Google": "Зарегистрироваться через Google",
    "Login with Google": "Войти через Google",
    "Failed to register with Google. Try again.":
      "Не удалось зарегистрироваться через Google. Попробуйте еще раз.",
    "Failed to login with Google. Try again.":
      "Не удалось войти через Google. Попробуйте еще раз.",
    Instructions: "Инструкции",
    "Privacy Policy": "Политика конфиденциальности",
    "YouTube Video URL (optional)": "URL видео на YouTube (необязательно)",
    "Invalid YouTube URL": "Недопустимый URL YouTube",
    "Video Tutorial": "Видеоурок",
    Username: "Имя пользователя",
    "Enter your username": "Введите ваше имя пользователя",
    "Account Settings": "Настройки аккаунта",
    "Current Password": "Текущий пароль",
    "Enter your current password": "Введите ваш текущий пароль",
    "New Password": "Новый пароль",
    "Enter your new password": "Введите ваш новый пароль",
    "Confirm New Password": "Подтвердите новый пароль",
    "Repeat your new password": "Повторите ваш новый пароль",
    "Update Password": "Обновить пароль",
    "Delete Account": "Удалить аккаунт",
    "Confirm Account Deletion": "Подтвердить удаление аккаунта",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "Вы уверены, что хотите удалить свою учетную запись? Это действие нельзя отменить, и все ваши рецепты будут удалены.",
    Cancel: "Отмена",
    "My Profile": "Мой профиль",
    "Update Username": "Обновить имя пользователя",
    "Username updated successfully.": "Имя пользователя успешно обновлено.",
    "Failed to update username. Try again.":
      "Не удалось обновить имя пользователя. Попробуйте еще раз.",
    "Password updated successfully.": "Пароль успешно обновлен.",
    "Failed to update password. Check your current password.":
      "Не удалось обновить пароль. Проверьте текущий пароль.",
    "Account deleted successfully.": "Аккаунт успешно удален.",
    "Failed to delete account. Check your current password.":
      "Не удалось удалить аккаунт. Проверьте текущий пароль.",
    "Manage your account and view your recipes!":
      "Управляйте своим аккаунтом и просматривайте свои рецепты!",
    "Failed to register: ": "Не удалось зарегистрироваться: ",
    "Failed to register with Google: ":
      "Не удалось зарегистрироваться через Google: ",
    "Invalid email or password: ":
      "Неверный адрес электронной почты или пароль: ",
    "Failed to login with Google: ": "Не удалось войти через Google: ",
    "Username must be 20 characters or less.":
      "Имя пользователя должно содержать не более 20 символов.",
    "Session expired. Please log in again.":
      "Сессия истекла. Пожалуйста, войдите снова.",
    "Error updating password:": "Ошибка при обновлении пароля:",
    "The current password is incorrect.": "Текущий пароль неверный.",
    "Too many attempts. Please try again later.":
      "Слишком много попыток. Попробуйте позже.",
    "Password should be at least 6 characters.":
      "Пароль должен содержать не менее 6 символов.",
    "Failed to update password: ": "Не удалось обновить пароль: ",
    "Please log in to add a comment.":
      "Пожалуйста, войдите, чтобы добавить комментарий.",
    "Invalid email or password": "Неверный адрес электронной почты или пароль",
    Author: "Автор",
  },
  ja: {
    Home: "ホーム",
    "Add Recipe": "レシピを追加",
    Profile: "プロフィール",
    Admin: "管理者",
    Logout: "ログアウト",
    Login: "ログイン",
    Register: "登録",
    "Recipe Sharing": "レシピ共有",
    "My Recipes": "私のレシピ",
    View: "見る",
    Edit: "編集",
    Delete: "削除",
    "Explore Recipes": "レシピを探す",
    "Search recipes...": "レシピを検索...",
    "All Categories": "すべてのカテゴリ",
    Breakfast: "朝食",
    Lunch: "昼食",
    Dinner: "夕食",
    Dessert: "デザート",
    "View Recipe": "レシピを見る",
    "Edit Recipe": "レシピを編集",
    "Update Recipe": "レシピを更新",
    "Add a Recipe": "レシピを追加する",
    Title: "タイトル",
    Description: "説明",
    Ingredients: "材料",
    Steps: "手順",
    Category: "カテゴリ",
    "Recipe Image (optional)": "レシピ画像（任意）",
    Comments: "コメント",
    "Post Comment": "コメントを投稿",
    "Add a comment...": "コメントを追加...",
    "Please log in to view your profile.":
      "プロフィールを見るにはログインしてください。",
    "Admin Panel - Manage Recipes": "管理パネル - レシピ管理",
    Email: "メール",
    Password: "パスワード",
    "Invalid email or password.": "メールまたはパスワードが無効です。",
    "Failed to register. Try again.":
      "登録に失敗しました。もう一度お試しください。",
    "Repeat Password": "パスワードを再入力",
    "Repeat your password": "パスワードをもう一度入力してください",
    "Passwords do not match.": "パスワードが一致しません。",
    "Enter your email": "メールアドレスを入力してください",
    "Enter your password": "パスワードを入力してください",
    "Recipe title": "レシピのタイトル",
    "Recipe description": "レシピの説明",
    "Recipe ingredients": "レシピの材料",
    "Recipe steps": "レシピの手順",
    "Recipe category": "レシピのカテゴリ",
    "Recipe image": "レシピの画像",
    "Recipe comments": "レシピのコメント",
    "Post a comment": "コメントを投稿する",
    "Add a comment": "コメントを追加する",
    "Describe your recipe": "レシピを説明してください",
    "List ingredients, one per line": "材料を1行ずつリストしてください",
    "List steps, one per line": "手順を1行ずつリストしてください",
    "Select a category": "カテゴリを選択してください",
    Previous: "前へ",
    Next: "次へ",
    "No recipes found.": "レシピが見つかりませんでした。",
    "No comments yet.": "まだコメントはありません。",
    "Recipe App": "レシピ共有プラットフォーム",
    "Update your recipe details.": "レシピの詳細を更新してください。",
    "Share your favorite recipe with the world!":
      "お気に入りのレシピを世界と共有しましょう！",
    "Discover and share amazing recipes!":
      "素晴らしいレシピを見つけ、共有しましょう！",
    "Log in to access your recipes!":
      "レシピにアクセスするにはログインしてください！",
    "Manage all recipes as an admin.":
      "管理者としてすべてのレシピを管理してください。",
    "View your personal recipe collection!":
      "個人的なレシピコレクションをご覧ください！",
    "Create an account to share your recipes!":
      "アカウントを作成してレシピを共有しましょう！",
    "Related Recipes": "関連レシピ",
    "Recipe not found.": "レシピが見つかりませんでした。",
    "404 - Page Not Found": "404 - ページが見つかりません",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "申し訳ありません。お探しのページは存在しないか、移動しました。",
    "Back to Home": "ホームに戻る",
    "Sort by...": "並べ替え...",
    "Alphabetical (A-Z)": "アルファベット順 (A-Z)",
    "Alphabetical (Z-A)": "アルファベット順 (Z-A)",
    "Date (Oldest First)": "日付 (古い順)",
    "Date (Newest First)": "日付 (新しい順)",
    "Register with Google": "Googleで登録",
    "Login with Google": "Googleでログイン",
    "Failed to register with Google. Try again.":
      "Googleでの登録に失敗しました。もう一度お試しください。",
    "Failed to login with Google. Try again.":
      "Googleでのログインに失敗しました。もう一度お試しください。",
    Instructions: "手順",
    "Privacy Policy": "プライバシーポリシー",
    "YouTube Video URL (optional)": "YouTubeビデオのURL（任意）",
    "Invalid YouTube URL": "無効なYouTube URL",
    "Video Tutorial": "ビデオチュートリアル",
    Username: "ユーザー名",
    "Enter your username": "ユーザー名を入力してください",
    "Account Settings": "アカウント設定",
    "Current Password": "現在のパスワード",
    "Enter your current password": "現在のパスワードを入力してください",
    "New Password": "新しいパスワード",
    "Enter your new password": "新しいパスワードを入力してください",
    "Confirm New Password": "新しいパスワードを確認",
    "Repeat your new password": "新しいパスワードを再入力してください",
    "Update Password": "パスワードを更新",
    "Delete Account": "アカウントを削除",
    "Confirm Account Deletion": "アカウント削除の確認",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "本当にアカウントを削除しますか？この操作は元に戻せず、すべてのレシピが削除されます。",
    Cancel: "キャンセル",
    "My Profile": "私のプロフィール",
    "Update Username": "ユーザー名を更新",
    "Username updated successfully.": "ユーザー名が正常に更新されました。",
    "Failed to update username. Try again.":
      "ユーザー名の更新に失敗しました。もう一度お試しください。",
    "Password updated successfully.": "パスワードが正常に更新されました。",
    "Failed to update password. Check your current password.":
      "パスワードの更新に失敗しました。現在のパスワードを確認してください。",
    "Account deleted successfully.": "アカウントが正常に削除されました。",
    "Failed to delete account. Check your current password.":
      "アカウントの削除に失敗しました。現在のパスワードを確認してください。",
    "Manage your account and view your recipes!":
      "アカウントを管理し、あなたのレシピをご覧ください！",
    "Failed to register: ": "登録に失敗しました：",
    "Failed to register with Google: ": "Googleでの登録に失敗しました：",
    "Invalid email or password: ": "メールまたはパスワードが無効です：",
    "Failed to login with Google: ": "Googleでのログインに失敗しました：",
    "Username must be 20 characters or less.":
      "ユーザー名は20文字以下でなければなりません。",
    "Session expired. Please log in again.":
      "セッションが期限切れです。もう一度ログインしてください。",
    "Error updating password:": "パスワード更新エラー：",
    "The current password is incorrect.": "現在のパスワードが間違っています。",
    "Too many attempts. Please try again later.":
      "試行回数が多すぎます。後でもう一度お試しください。",
    "Password should be at least 6 characters.":
      "パスワードは6文字以上である必要があります。",
    "Failed to update password: ": "パスワードの更新に失敗しました：",
    "Please log in to add a comment.":
      "コメントを追加するにはログインしてください。",
    "Invalid email or password": "メールまたはパスワードが無効です",
    Author: "著者",
  },
  ko: {
    Home: "홈",
    "Add Recipe": "레시피 추가",
    Profile: "프로필",
    Admin: "관리자",
    Logout: "로그아웃",
    Login: "로그인",
    Register: "회원가입",
    "Recipe Sharing": "레시피 공유",
    "My Recipes": "내 레시피",
    View: "보기",
    Edit: "편집",
    Delete: "삭제",
    "Explore Recipes": "레시피 탐색",
    "Search recipes...": "레시피 검색...",
    "All Categories": "모든 카테고리",
    Breakfast: "아침 식사",
    Lunch: "점심 식사",
    Dinner: "저녁 식사",
    Dessert: "디저트",
    "View Recipe": "레시피 보기",
    "Edit Recipe": "레시피 편집",
    "Update Recipe": "레시피 업데이트",
    "Add a Recipe": "레시피 추가하기",
    Title: "제목",
    Description: "설명",
    Ingredients: "재료",
    Steps: "단계",
    Category: "카테고리",
    "Recipe Image (optional)": "레시피 이미지 (선택 사항)",
    Comments: "댓글",
    "Post Comment": "댓글 게시",
    "Add a comment...": "댓글 추가...",
    "Please log in to view your profile.": "프로필을 보려면 로그인하세요.",
    "Admin Panel - Manage Recipes": "관리자 패널 - 레시피 관리",
    Email: "이메일",
    Password: "비밀번호",
    "Invalid email or password.": "잘못된 이메일 또는 비밀번호입니다.",
    "Failed to register. Try again.":
      "회원가입에 실패했습니다. 다시 시도하세요.",
    "Repeat Password": "비밀번호 재입력",
    "Repeat your password": "비밀번호를 다시 입력하세요",
    "Passwords do not match.": "비밀번호가 일치하지 않습니다.",
    "Enter your email": "이메일을 입력하세요",
    "Enter your password": "비밀번호를 입력하세요",
    "Recipe title": "레시피 제목",
    "Recipe description": "레시피 설명",
    "Recipe ingredients": "레시피 재료",
    "Recipe steps": "레시피 단계",
    "Recipe category": "레시피 카테고리",
    "Recipe image": "레시피 이미지",
    "Recipe comments": "레시피 댓글",
    "Post a comment": "댓글 게시하기",
    "Add a comment": "댓글 추가하기",
    "Describe your recipe": "레시피를 설명하세요",
    "List ingredients, one per line": "재료를 한 줄에 하나씩 나열하세요",
    "List steps, one per line": "단계를 한 줄에 하나씩 나열하세요",
    "Select a category": "카테고리를 선택하세요",
    Previous: "이전",
    Next: "다음",
    "No recipes found.": "레시피를 찾을 수 없습니다.",
    "No comments yet.": "아직 댓글이 없습니다.",
    "Recipe App": "레시피 공유 플랫폼",
    "Update your recipe details.": "레시피 세부 정보를 업데이트하세요.",
    "Share your favorite recipe with the world!":
      "당신의 좋아하는 레시피를 세상과 공유하세요!",
    "Discover and share amazing recipes!":
      "놀라운 레시피를 발견하고 공유하세요!",
    "Log in to access your recipes!": "레시피에 접근하려면 로그인하세요!",
    "Manage all recipes as an admin.": "관리자로 모든 레시피를 관리하세요.",
    "View your personal recipe collection!": "개인 레시피 컬렉션을 보세요!",
    "Create an account to share your recipes!":
      "레시피를 공유하려면 계정을 만드세요!",
    "Related Recipes": "관련 레시피",
    "Recipe not found.": "레시피를 찾을 수 없습니다.",
    "404 - Page Not Found": "404 - 페이지를 찾을 수 없습니다",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "죄송합니다. 찾으시는 페이지가 존재하지 않거나 이동되었습니다.",
    "Back to Home": "홈으로 돌아가기",
    "Sort by...": "정렬 기준...",
    "Alphabetical (A-Z)": "알파벳순 (A-Z)",
    "Alphabetical (Z-A)": "알파벳순 (Z-A)",
    "Date (Oldest First)": "날짜 (오래된 순)",
    "Date (Newest First)": "날짜 (최신 순)",
    "Register with Google": "Google로 회원가입",
    "Login with Google": "Google로 로그인",
    "Failed to register with Google. Try again.":
      "Google로 회원가입에 실패했습니다. 다시 시도하세요.",
    "Failed to login with Google. Try again.":
      "Google로 로그인에 실패했습니다. 다시 시도하세요.",
    Instructions: "지침",
    "Privacy Policy": "개인정보 처리방침",
    "YouTube Video URL (optional)": "YouTube 비디오 URL (선택 사항)",
    "Invalid YouTube URL": "잘못된 YouTube URL",
    "Video Tutorial": "비디오 튜토리얼",
    Username: "사용자 이름",
    "Enter your username": "사용자 이름을 입력하세요",
    "Account Settings": "계정 설정",
    "Current Password": "현재 비밀번호",
    "Enter your current password": "현재 비밀번호를 입력하세요",
    "New Password": "새 비밀번호",
    "Enter your new password": "새 비밀번호를 입력하세요",
    "Confirm New Password": "새 비밀번호 확인",
    "Repeat your new password": "새 비밀번호를 다시 입력하세요",
    "Update Password": "비밀번호 업데이트",
    "Delete Account": "계정 삭제",
    "Confirm Account Deletion": "계정 삭제 확인",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "정말로 계정을 삭제하시겠습니까? 이 작업은 취소할 수 없으며 모든 레시피가 삭제됩니다.",
    Cancel: "취소",
    "My Profile": "내 프로필",
    "Update Username": "사용자 이름 업데이트",
    "Username updated successfully.":
      "사용자 이름이 성공적으로 업데이트되었습니다.",
    "Failed to update username. Try again.":
      "사용자 이름 업데이트에 실패했습니다. 다시 시도하세요.",
    "Password updated successfully.":
      "비밀번호가 성공적으로 업데이트되었습니다.",
    "Failed to update password. Check your current password.":
      "비밀번호 업데이트에 실패했습니다. 현재 비밀번호를 확인하세요.",
    "Account deleted successfully.": "계정이 성공적으로 삭제되었습니다.",
    "Failed to delete account. Check your current password.":
      "계정 삭제에 실패했습니다. 현재 비밀번호를 확인하세요.",
    "Manage your account and view your recipes!":
      "계정을 관리하고 레시피를 확인하세요!",
    "Failed to register: ": "회원가입에 실패했습니다: ",
    "Failed to register with Google: ": "Google로 회원가입에 실패했습니다: ",
    "Invalid email or password: ": "잘못된 이메일 또는 비밀번호입니다: ",
    "Failed to login with Google: ": "Google로 로그인에 실패했습니다: ",
    "Username must be 20 characters or less.":
      "사용자 이름은 20자 이하여야 합니다.",
    "Session expired. Please log in again.":
      "세션이 만료되었습니다. 다시 로그인하세요.",
    "Error updating password:": "비밀번호 업데이트 오류:",
    "The current password is incorrect.": "현재 비밀번호가 잘못되었습니다.",
    "Too many attempts. Please try again later.":
      "시도 횟수가 너무 많습니다. 나중에 다시 시도하세요.",
    "Password should be at least 6 characters.":
      "비밀번호는 최소 6자 이상이어야 합니다.",
    "Failed to update password: ": "비밀번호 업데이트에 실패했습니다: ",
    "Please log in to add a comment.": "댓글을 추가하려면 로그인하세요.",
    "Invalid email or password": "잘못된 이메일 또는 비밀번호입니다",
    Author: "저자",
  },
  zh: {
    Home: "首页",
    "Add Recipe": "添加食谱",
    Profile: "个人资料",
    Admin: "管理员",
    Logout: "退出",
    Login: "登录",
    Register: "注册",
    "Recipe Sharing": "食谱分享",
    "My Recipes": "我的食谱",
    View: "查看",
    Edit: "编辑",
    Delete: "删除",
    "Explore Recipes": "探索食谱",
    "Search recipes...": "搜索食谱...",
    "All Categories": "所有类别",
    Breakfast: "早餐",
    Lunch: "午餐",
    Dinner: "晚餐",
    Dessert: "甜点",
    "View Recipe": "查看食谱",
    "Edit Recipe": "编辑食谱",
    "Update Recipe": "更新食谱",
    "Add a Recipe": "添加一个食谱",
    Title: "标题",
    Description: "描述",
    Ingredients: "原料",
    Steps: "步骤",
    Category: "类别",
    "Recipe Image (optional)": "食谱图片（可选）",
    Comments: "评论",
    "Post Comment": "发布评论",
    "Add a comment...": "添加评论...",
    "Please log in to view your profile.": "请登录以查看您的个人资料。",
    "Admin Panel - Manage Recipes": "管理面板 - 管理食谱",
    Email: "电子邮件",
    Password: "密码",
    "Invalid email or password.": "电子邮件或密码无效。",
    "Failed to register. Try again.": "注册失败。请重试。",
    "Repeat Password": "重复密码",
    "Repeat your password": "请再次输入您的密码",
    "Passwords do not match.": "密码不匹配。",
    "Enter your email": "输入您的电子邮件",
    "Enter your password": "输入您的密码",
    "Recipe title": "食谱标题",
    "Recipe description": "食谱描述",
    "Recipe ingredients": "食谱原料",
    "Recipe steps": "食谱步骤",
    "Recipe category": "食谱类别",
    "Recipe image": "食谱图片",
    "Recipe comments": "食谱评论",
    "Post a comment": "发布一个评论",
    "Add a comment": "添加一个评论",
    "Describe your recipe": "描述您的食谱",
    "List ingredients, one per line": "列出原料，每行一个",
    "List steps, one per line": "列出步骤，每行一个",
    "Select a category": "选择一个类别",
    Previous: "上一页",
    Next: "下一页",
    "No recipes found.": "未找到食谱。",
    "No comments yet.": "暂无评论。",
    "Recipe App": "食谱分享平台",
    "Update your recipe details.": "更新您的食谱详情。",
    "Share your favorite recipe with the world!": "与世界分享您喜爱的食谱！",
    "Discover and share amazing recipes!": "发现并分享精彩的食谱！",
    "Log in to access your recipes!": "登录以访问您的食谱！",
    "Manage all recipes as an admin.": "以管理员身份管理所有食谱。",
    "View your personal recipe collection!": "查看您的个人食谱收藏！",
    "Create an account to share your recipes!": "创建账户以分享您的食谱！",
    "Related Recipes": "相关食谱",
    "Recipe not found.": "未找到食谱。",
    "404 - Page Not Found": "404 - 页面未找到",
    "Sorry, the page you are looking for does not exist or has been moved.":
      "抱歉，您寻找的页面不存在或已被移动。",
    "Back to Home": "返回首页",
    "Sort by...": "排序方式...",
    "Alphabetical (A-Z)": "按字母顺序 (A-Z)",
    "Alphabetical (Z-A)": "按字母顺序 (Z-A)",
    "Date (Oldest First)": "日期 (最早优先)",
    "Date (Newest First)": "日期 (最新优先)",
    "Register with Google": "使用 Google 注册",
    "Login with Google": "使用 Google 登录",
    "Failed to register with Google. Try again.":
      "使用 Google 注册失败。请重试。",
    "Failed to login with Google. Try again.": "使用 Google 登录失败。请重试。",
    Instructions: "说明",
    "Privacy Policy": "隐私政策",
    "YouTube Video URL (optional)": "YouTube 视频 URL（可选）",
    "Invalid YouTube URL": "无效的 YouTube URL",
    "Video Tutorial": "视频教程",
    Username: "用户名",
    "Enter your username": "输入您的用户名",
    "Account Settings": "账户设置",
    "Current Password": "当前密码",
    "Enter your current password": "输入当前密码",
    "New Password": "新密码",
    "Enter your new password": "输入新密码",
    "Confirm New Password": "确认新密码",
    "Repeat your new password": "重复新密码",
    "Update Password": "更新密码",
    "Delete Account": "删除账户",
    "Confirm Account Deletion": "确认删除账户",
    "Are you sure you want to delete your account? This action cannot be undone, and all your recipes will be deleted.":
      "您确定要删除您的账户吗？此操作无法撤消，所有食谱将被删除。",
    Cancel: "取消",
    "My Profile": "我的个人资料",
    "Update Username": "更新用户名",
    "Username updated successfully.": "用户名更新成功。",
    "Failed to update username. Try again.": "更新用户名失败。请重试。",
    "Password updated successfully.": "密码更新成功。",
    "Failed to update password. Check your current password.":
      "更新密码失败。请检查当前密码。",
    "Account deleted successfully.": "账户删除成功。",
    "Failed to delete account. Check your current password.":
      "删除账户失败。请检查当前密码。",
    "Manage your account and view your recipes!":
      "管理您的账户并查看您的食谱！",
    "Failed to register: ": "注册失败：",
    "Failed to register with Google: ": "使用 Google 注册失败：",
    "Invalid email or password: ": "电子邮件或密码无效：",
    "Failed to login with Google: ": "使用 Google 登录失败：",
    "Username must be 20 characters or less.": "用户名必须为20个字符或更少。",
    "Session expired. Please log in again.": "会话已过期。请重新登录。",
    "Error updating password:": "更新密码错误：",
    "The current password is incorrect.": "当前密码不正确。",
    "Too many attempts. Please try again later.": "尝试次数过多。请稍后再试。",
    "Password should be at least 6 characters.": "密码应至少为6个字符。",
    "Failed to update password: ": "更新密码失败：",
    "Please log in to add a comment.": "请登录以添加评论。",
    "Invalid email or password": "电子邮件或密码无效",
    Author: "作者",
  },
};

// Create Language Context
const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  // Initialize language from localStorage, default to "en" if not found
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem("language");
    return savedLanguage && translations[savedLanguage] ? savedLanguage : "vi";
  });

  // Save language to localStorage whenever it changes
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const translate = (key) => {
    return translations[language][key] || key; // Return key if translation not found
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook to use the Language Context
export const useLanguage = () => useContext(LanguageContext);
